import { useRef, useState, useEffect } from 'react';
import { useAuth } from '@clerk/clerk-react';
import { api } from '../lib/api';
import type { TfResponse, PublishRecord, Thread } from '../types';
import { Share2, Loader2, CheckCircle, AlertCircle, ImageIcon, Video } from 'lucide-react';
import { cn } from '../lib/utils';

interface PublishBarProps {
  slug: string;
  thread: Thread;
  onPublished?: () => void;
}

const POLL_INTERVAL_MS = 4000;
const POLL_MAX_ATTEMPTS = 30; // 30 × 4s = 2 min max

export default function PublishBar({ slug, thread, onPublished }: PublishBarProps) {
  const { getToken } = useAuth();
  const [publishingTo, setPublishingTo] = useState<string | null>(null);
  const [publishStatus, setPublishStatus] = useState<Record<string, 'idle' | 'publishing' | 'processing' | 'done' | 'failed'>>({});
  const [recordIds, setRecordIds] = useState<Record<string, string>>({});
  const pollTimers = useRef<Record<string, ReturnType<typeof setTimeout>>>({});

  // On mount, load existing publish records for this asset and restore status
  useEffect(() => {
    if (!thread.active_draft_id) return;
    let cancelled = false;
    (async () => {
      const token = await getToken();
      const res = await api.get<TfResponse<PublishRecord[]>>(
        `/api/workspaces/${slug}/publish/history`,
        token ?? undefined
      );
      if (cancelled || !res.success || !res.data) return;

      const assetRecords = res.data.filter((r) => r.asset_id === thread.active_draft_id);
      // Keep only the latest record per platform
      const latest: Record<string, PublishRecord> = {};
      for (const r of assetRecords) {
        if (!latest[r.platform] || r.created_at > latest[r.platform].created_at) {
          latest[r.platform] = r;
        }
      }

      const ids: Record<string, string> = {};
      const statuses: Record<string, 'idle' | 'processing' | 'done' | 'failed'> = {};
      for (const [platform, record] of Object.entries(latest)) {
        ids[platform] = record.id;
        if (record.status === 'published') statuses[platform] = 'done';
        else if (record.status === 'failed') statuses[platform] = 'failed';
        else if (record.status === 'processing' || record.status === 'pending') statuses[platform] = 'processing';
      }
      setRecordIds(ids);
      setPublishStatus(statuses);

      // Resume polling for any still-processing record
      for (const [platform, record] of Object.entries(latest)) {
        if (record.status === 'processing' || record.status === 'pending') {
          pollUntilDone(platform as 'instagram' | 'tiktok', record.id);
        }
      }
    })();
    return () => { cancelled = true; };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [thread.active_draft_id]);

  const canPublish = thread.status === 'ready' && thread.active_draft_id;

  async function pollUntilDone(platform: 'instagram' | 'tiktok', recordId: string, attempt = 0) {
    if (attempt >= POLL_MAX_ATTEMPTS) {
      setPublishStatus((s) => ({ ...s, [platform]: 'failed' }));
      return;
    }
    const token = await getToken();
    const res = await api.get<TfResponse<PublishRecord>>(
      `/api/workspaces/${slug}/publish/status/${recordId}`,
      token ?? undefined
    );
    if (res.success && res.data) {
      if (res.data.status === 'published') {
        setPublishStatus((s) => ({ ...s, [platform]: 'done' }));
        onPublished?.();
        return;
      }
      if (res.data.status === 'failed') {
        setPublishStatus((s) => ({ ...s, [platform]: 'failed' }));
        return;
      }
    }
    // Still processing — schedule next poll
    pollTimers.current[platform] = setTimeout(
      () => pollUntilDone(platform, recordId, attempt + 1),
      POLL_INTERVAL_MS
    );
  }

  async function handlePublish(platform: 'instagram' | 'tiktok') {
    if (!canPublish) return;
    setPublishingTo(platform);
    setPublishStatus((s) => ({ ...s, [platform]: 'publishing' }));

    const token = await getToken();

    try {
      const res = await api.post<TfResponse<PublishRecord>>(
        `/api/workspaces/${slug}/publish/${platform}`,
        { caption: 'Generated by CreatorOS' },
        token ?? undefined
      );

      if (res.success && res.data) {
        setRecordIds((r) => ({ ...r, [platform]: res.data!.id }));
        if (res.data.status === 'published') {
          // Image — published synchronously
          setPublishStatus((s) => ({ ...s, [platform]: 'done' }));
          onPublished?.();
        } else if (res.data.status === 'processing') {
          // Video — container created, needs polling
          setPublishStatus((s) => ({ ...s, [platform]: 'processing' }));
          pollUntilDone(platform, res.data.id);
        } else {
          setPublishStatus((s) => ({ ...s, [platform]: 'failed' }));
        }
      } else {
        setPublishStatus((s) => ({ ...s, [platform]: 'failed' }));
      }
    } catch {
      setPublishStatus((s) => ({ ...s, [platform]: 'failed' }));
    } finally {
      setPublishingTo(null);
    }
  }

  if (!canPublish && thread.status !== 'ready') return null;

  const statusIcon = (p: string) => {
    const s = publishStatus[p] ?? 'idle';
    if (s === 'publishing') return <Loader2 size={14} className='animate-spin' />;
    if (s === 'processing') return <Loader2 size={14} className='animate-spin' />;
    if (s === 'done') return <CheckCircle size={14} className='text-green-400' />;
    if (s === 'failed') return <AlertCircle size={14} className='text-red-400' />;
    return <Share2 size={14} />;
  };

  const statusLabel = (p: 'instagram' | 'tiktok') => {
    const s = publishStatus[p] ?? 'idle';
    if (s === 'processing') return 'Processing…';
    return p === 'instagram' ? 'Instagram' : 'TikTok';
  };

  return (
    <div className='border-t border-gray-200 dark:border-gray-800 bg-gray-50/50 dark:bg-gray-900/50 px-4 py-3'>
      <div className='flex items-center gap-2'>
        <div className='flex items-center gap-1.5 text-xs text-gray-500 dark:text-gray-400'>
          {thread.media_type === 'image' ? (
            <ImageIcon size={13} />
          ) : (
            <Video size={13} />
          )}
          <span>Ready to publish</span>
        </div>
        <div className='flex-1' />
        {(['instagram', 'tiktok'] as const).map((platform) => (
          <button
            key={platform}
            onClick={() => handlePublish(platform)}
            disabled={!!publishingTo || publishStatus[platform] === 'done' || publishStatus[platform] === 'processing'}
            className={cn(
              'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all',
              publishStatus[platform] === 'done'
                ? 'bg-green-900/30 text-green-400 border border-green-700/30'
                : publishStatus[platform] === 'failed'
                ? 'bg-red-900/30 text-red-400 border border-red-700/30'
                : publishStatus[platform] === 'processing'
                ? 'bg-yellow-900/30 text-yellow-400 border border-yellow-700/30'
                : platform === 'instagram'
                ? 'bg-gradient-to-r from-pink-600 to-orange-500 text-white hover:opacity-90 disabled:opacity-50'
                : 'bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-white border border-gray-300 dark:border-gray-700 hover:bg-gray-200 dark:hover:bg-gray-700 disabled:opacity-50'
            )}
          >
            {statusIcon(platform)}
            {statusLabel(platform)}
          </button>
        ))}
      </div>
    </div>
  );
}
