import { useState } from 'react';
import type { Thread } from '../types';
import { usePublishStatus } from '../hooks/usePublishStatus';
import { Share2, Loader2, CheckCircle, AlertCircle, ImageIcon, Video } from 'lucide-react';
import { cn } from '../lib/utils';

interface PublishBarProps {
  slug: string;
  thread: Thread;
  onPublished?: () => void;
}

export default function PublishBar({ slug, thread, onPublished }: PublishBarProps) {
  const [publishingTo, setPublishingTo] = useState<string | null>(null);
  const { status, publish } = usePublishStatus(slug, thread.active_draft_id ?? undefined);

  const canPublish = thread.status === 'ready' && thread.active_draft_id;

  async function handlePublish(platform: 'instagram' | 'tiktok') {
    if (!canPublish) return;
    setPublishingTo(platform);
    await publish(platform, { assetId: thread.active_draft_id, caption: 'Generated by CreatorOS' });
    setPublishingTo(null);
    if (status[platform] === 'done') onPublished?.();
  }

  if (!canPublish && thread.status !== 'ready') return null;

  const statusIcon = (p: string) => {
    const s = status[p] ?? 'idle';
    if (s === 'publishing' || s === 'processing') return <Loader2 size={14} className='animate-spin' />;
    if (s === 'done') return <CheckCircle size={14} className='text-green-400' />;
    if (s === 'failed') return <AlertCircle size={14} className='text-red-400' />;
    return <Share2 size={14} />;
  };

  const statusLabel = (p: 'instagram' | 'tiktok') => {
    const s = status[p] ?? 'idle';
    if (s === 'processing') return 'Processing…';
    return p === 'instagram' ? 'Instagram' : 'TikTok';
  };

  return (
    <div className='border-t border-gray-200 dark:border-gray-800 bg-gray-50/50 dark:bg-gray-900/50 px-4 py-3'>
      <div className='flex items-center gap-2'>
        <div className='flex items-center gap-1.5 text-xs text-gray-500 dark:text-gray-400'>
          {thread.media_type === 'image' ? (
            <ImageIcon size={13} />
          ) : (
            <Video size={13} />
          )}
          <span>Ready to publish</span>
        </div>
        <div className='flex-1' />
        {(['instagram', 'tiktok'] as const).map((platform) => {
          const s = status[platform] ?? 'idle';
          return (
            <button
              key={platform}
              onClick={() => handlePublish(platform)}
              disabled={!!publishingTo || s === 'done' || s === 'processing'}
              className={cn(
                'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all',
                s === 'done'
                  ? 'bg-green-900/30 text-green-400 border border-green-700/30'
                  : s === 'failed'
                  ? 'bg-red-900/30 text-red-400 border border-red-700/30'
                  : s === 'processing'
                  ? 'bg-yellow-900/30 text-yellow-400 border border-yellow-700/30'
                  : platform === 'instagram'
                  ? 'bg-gradient-to-r from-pink-600 to-orange-500 text-white hover:opacity-90 disabled:opacity-50'
                  : 'bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-white border border-gray-300 dark:border-gray-700 hover:bg-gray-200 dark:hover:bg-gray-700 disabled:opacity-50'
              )}
            >
              {statusIcon(platform)}
              {statusLabel(platform)}
            </button>
          );
        })}
      </div>
    </div>
  );
}
