import { useState } from 'react';
import { useAuth } from '@clerk/clerk-react';
import { api } from '../lib/api';
import type { TfResponse, PublishRecord, Thread } from '../types';
import { Share2, Loader2, CheckCircle, AlertCircle, ImageIcon, Video } from 'lucide-react';
import { cn } from '../lib/utils';

interface PublishBarProps {
  slug: string;
  thread: Thread;
  onPublished?: () => void;
}

export default function PublishBar({ slug, thread, onPublished }: PublishBarProps) {
  const { getToken } = useAuth();
  const [publishingTo, setPublishingTo] = useState<string | null>(null);
  const [publishStatus, setPublishStatus] = useState<Record<string, 'idle' | 'publishing' | 'done' | 'failed'>>({});

  const canPublish = thread.status === 'ready' && thread.active_draft_id;

  async function handlePublish(platform: 'instagram' | 'tiktok') {
    if (!canPublish) return;
    setPublishingTo(platform);
    setPublishStatus((s) => ({ ...s, [platform]: 'publishing' }));

    const token = await getToken();

    try {
      const res = await api.post<TfResponse<PublishRecord>>(
        `/api/workspaces/${slug}/publish/${platform}`,
        { caption: 'Generated by CreatorOS' },
        token ?? undefined
      );

      if (res.success) {
        setPublishStatus((s) => ({ ...s, [platform]: 'done' }));
        onPublished?.();
      } else {
        setPublishStatus((s) => ({ ...s, [platform]: 'failed' }));
      }
    } catch {
      setPublishStatus((s) => ({ ...s, [platform]: 'failed' }));
    } finally {
      setPublishingTo(null);
    }
  }

  if (!canPublish && thread.status !== 'ready') return null;

  const statusIcon = (p: string) => {
    const s = publishStatus[p] ?? 'idle';
    if (s === 'publishing') return <Loader2 size={14} className='animate-spin' />;
    if (s === 'done') return <CheckCircle size={14} className='text-green-400' />;
    if (s === 'failed') return <AlertCircle size={14} className='text-red-400' />;
    return <Share2 size={14} />;
  };

  return (
    <div className='border-t border-gray-800 bg-gray-900/50 px-4 py-3'>
      <div className='flex items-center gap-2'>
        <div className='flex items-center gap-1.5 text-xs text-gray-400'>
          {thread.media_type === 'image' ? (
            <ImageIcon size={13} />
          ) : (
            <Video size={13} />
          )}
          <span>Ready to publish</span>
        </div>
        <div className='flex-1' />
        {(['instagram', 'tiktok'] as const).map((platform) => (
          <button
            key={platform}
            onClick={() => handlePublish(platform)}
            disabled={!!publishingTo || publishStatus[platform] === 'done'}
            className={cn(
              'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all',
              publishStatus[platform] === 'done'
                ? 'bg-green-900/30 text-green-400 border border-green-700/30'
                : publishStatus[platform] === 'failed'
                ? 'bg-red-900/30 text-red-400 border border-red-700/30'
                : platform === 'instagram'
                ? 'bg-gradient-to-r from-pink-600 to-orange-500 text-white hover:opacity-90 disabled:opacity-50'
                : 'bg-gray-800 text-white border border-gray-700 hover:bg-gray-700 disabled:opacity-50'
            )}
          >
            {statusIcon(platform)}
            {platform === 'instagram' ? 'Instagram' : 'TikTok'}
          </button>
        ))}
      </div>
    </div>
  );
}
